name = "turms"
main = ".output/server/index.mjs"
compatibility_date = "2022-09-10"
route = "turms.gravitalia.com"

rules = [
    { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

secrets_store_secrets = [
  { binding = "TURMS_JWT_PRIVATE_KEY", store_id= "1ae16342dea540b582b170935a0f39af", secret_name = "TURMS_JWT_PRIVATE_KEY" }
]

[assets]
directory = ".output/public"

compatibility_flags = [ "nodejs_compat", "nodejs_compat_v2" ]

[observability]
enabled = false